# Generated by Django 5.1.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='schema_type',
            field=models.CharField(default='resume', max_length=100),
        ),
    ]
